apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rest-feed-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rest-feed
    spec:
      containers:
        - name: rest-content-service
          image: gcr.io/alien-fold-180922/restfeed:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: rest_aggregator_url
              value: "http://rest-aggregator-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: rest-feed-service
spec:
  type: LoadBalancer
  selector:
    app: rest-feed
  ports:
   - port: 8080
     targetPort: 8080
     protocol: TCP
---
